name: Deploy

on:
  push:

jobs:
  github:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2 # 检出你在当前github工作空间的项目
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: Use yarn
        run: npm install -g yarn
      - name: install
        run: yarn
      - name: Build
        run: yarn build

  Cloudbase:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: Use yarn
        run: npm install -g yarn
      - name: install
        run: yarn
      - name: build
        run: yarn build
      - name: Deploy static to Tencent CloudBase
        id: deployStatic
        uses: TencentCloudBase/cloudbase-action@v1.1.1
        with:
          secretId: ${{ secrets.SECRET_ID }}
          secretKey: ${{ secrets.SECRET_KEY }}
          envId: ${{ secrets.ENV_ID }}
          staticSrcPath: dist
